#cloudinary:
 # cloud_name: ${CLOUDINARY_CLOUD_NAME}
  #api_key: ${CLOUDINARY_API_KEY}
  #api_secret: ${CLOUDINARY_API_SECRET}
spring:
  application:
    name: SOF3022_ASS_RestFul_API
  datasource:
    url: jdbc:sqlserver://localhost;database=J5Shop;encrypt=false;trustServerCertificate=true
    username: sa #${SPRING_DB_USERNAME}
    password: 123 #${SPRING_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
